package com.adrianocodenow.contatos2022.view;

import com.adrianocodenow.contatos2022.controller.ContatoCtrl;
import com.adrianocodenow.contatos2022.controller.StrNormalize;
import com.adrianocodenow.contatos2022.controller.TelefoneCtrl;
import com.adrianocodenow.contatos2022.controller.TipoTelefoneCtrl;
import com.adrianocodenow.contatos2022.dao.CriaTabelas;
import com.adrianocodenow.contatos2022.dao.EnderecoDao;
import com.adrianocodenow.contatos2022.dao.TelefoneDao;
import com.adrianocodenow.contatos2022.dao.TipoEnderecoDao;
import com.adrianocodenow.contatos2022.dao.TipoTelefoneDao;
import com.adrianocodenow.contatos2022.model.Contato;
import com.adrianocodenow.contatos2022.model.Endereco;
import com.adrianocodenow.contatos2022.model.Telefone;
import com.adrianocodenow.contatos2022.model.TipoEndereco;
import com.adrianocodenow.contatos2022.model.TipoTelefone;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author apereira
 */
public class ListaContatos extends javax.swing.JFrame {

    /**
     * Creates new form ListaContatos
     */
    public ListaContatos() {
        CriaTabelas.criaBancoDeDados();

        initComponents();
        lblMensagem.setText("");
        loadList2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstContatos = new javax.swing.JList<>();
        lblMensagem = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtSobrenome = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAddAddress = new javax.swing.JButton();
        btnDelAddr = new javax.swing.JButton();
        btnAddPhone = new javax.swing.JButton();
        btnDelPhone = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        edtCEP = new javax.swing.JTextField();
        edtBairro = new javax.swing.JTextField();
        edtCidade = new javax.swing.JTextField();
        edtEstado = new javax.swing.JTextField();
        edtPais = new javax.swing.JTextField();
        scrpEnderecos = new javax.swing.JScrollPane();
        lstEnderecos = new javax.swing.JList<>();
        edtTipoEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAddTipoEndereco = new javax.swing.JLabel();
        lblDelTipoEndereco = new javax.swing.JLabel();
        lblEditTipoEndereco = new javax.swing.JLabel();
        scrpTiposTelefones = new javax.swing.JScrollPane();
        lstTiposTelefones = new javax.swing.JList<>();
        scrpTelefones = new javax.swing.JScrollPane();
        lstTelefones = new javax.swing.JList<>();
        edtTipoTelefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblAddTipoTelefone = new javax.swing.JLabel();
        lblDelTipoTelefone = new javax.swing.JLabel();
        lblEditTipoTelefone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAddTelefone = new javax.swing.JLabel();
        lblDelTelefone = new javax.swing.JLabel();
        lblEditTelefone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstContatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstContatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstContatosMouseDragged(evt);
            }
        });
        lstContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstContatosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstContatosMouseReleased(evt);
            }
        });
        lstContatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstContatosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstContatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 620));

        lblMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMensagem.setText("LINHA DE MENSAGEM");
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 39, 338, 30));

        edtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtNome.setText("jTextField1");
        edtNome.setMaximumSize(new java.awt.Dimension(351, 30));
        edtNome.setMinimumSize(new java.awt.Dimension(351, 30));
        edtNome.setPreferredSize(new java.awt.Dimension(330, 30));
        edtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtNomeKeyReleased(evt);
            }
        });
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 100, 351, 30));

        edtSobrenome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtSobrenome.setText("jTextField1");
        edtSobrenome.setMaximumSize(new java.awt.Dimension(351, 30));
        edtSobrenome.setMinimumSize(new java.awt.Dimension(351, 30));
        edtSobrenome.setPreferredSize(new java.awt.Dimension(330, 30));
        edtSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtSobrenomeKeyReleased(evt);
            }
        });
        getContentPane().add(edtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 100, 351, 30));

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 64, 64));

        btnDel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDel.setText("-");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 5, 64, 64));

        btnOK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.setEnabled(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 5, 64, 64));

        btnCancel.setText("X");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 5, 64, 64));

        btnAddAddress.setText("+ End");
        btnAddAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAddressActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 5, 64, 64));

        btnDelAddr.setText("- End");
        btnDelAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAddrActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 5, 64, 64));

        btnAddPhone.setText("+ Tel");
        getContentPane().add(btnAddPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 5, 64, 64));

        btnDelPhone.setText("- Tel");
        getContentPane().add(btnDelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 5, 64, 64));

        btnSearch.setText("?");
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 5, 64, 64));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Sobrenome");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 70, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Contatos");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("MENSAGEM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 10, -1, -1));

        edtEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtEndereco.setText("jTextField1");
        edtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtEnderecoKeyReleased(evt);
            }
        });
        getContentPane().add(edtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 170, 351, 30));

        edtCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtCEP.setText("jTextField2");
        edtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCEPKeyReleased(evt);
            }
        });
        getContentPane().add(edtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 445, 351, 30));

        edtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtBairro.setText("jTextField2");
        edtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtBairroKeyReleased(evt);
            }
        });
        getContentPane().add(edtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 225, 351, 30));

        edtCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtCidade.setText("jTextField2");
        edtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCidadeKeyReleased(evt);
            }
        });
        getContentPane().add(edtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 280, 351, 30));

        edtEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtEstado.setText("jTextField2");
        edtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtEstadoKeyReleased(evt);
            }
        });
        getContentPane().add(edtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 335, 351, 30));

        edtPais.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtPais.setText("jTextField2");
        edtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtPaisKeyReleased(evt);
            }
        });
        getContentPane().add(edtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 390, 351, 30));

        scrpEnderecos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstEnderecos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEnderecos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstEnderecosMouseDragged(evt);
            }
        });
        lstEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEnderecosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstEnderecosMouseReleased(evt);
            }
        });
        lstEnderecos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstEnderecosKeyReleased(evt);
            }
        });
        scrpEnderecos.setViewportView(lstEnderecos);

        getContentPane().add(scrpEnderecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 340, 305));

        edtTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtTipoEndereco.setText("jTextField1");
        getContentPane().add(edtTipoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 340, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tipos de Endereço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Bairro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 205, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Cidade");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Estado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 315, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("País");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("CEP");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 425, -1, -1));

        lblAddTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTipoEndereco.setText("+");
        lblAddTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddTipoEnderecoMouseReleased(evt);
            }
        });
        getContentPane().add(lblAddTipoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 150, -1, -1));

        lblDelTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTipoEndereco.setText("-");
        lblDelTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDelTipoEnderecoMouseReleased(evt);
            }
        });
        getContentPane().add(lblDelTipoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 150, -1, -1));

        lblEditTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTipoEndereco.setText("Edit");
        lblEditTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditTipoEnderecoMouseReleased(evt);
            }
        });
        getContentPane().add(lblEditTipoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        scrpTiposTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstTiposTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTiposTelefones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseDragged(evt);
            }
        });
        lstTiposTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseReleased(evt);
            }
        });
        lstTiposTelefones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstTiposTelefonesKeyReleased(evt);
            }
        });
        scrpTiposTelefones.setViewportView(lstTiposTelefones);

        getContentPane().add(scrpTiposTelefones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 340, 210));

        lstTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTelefones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseDragged(evt);
            }
        });
        lstTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseReleased(evt);
            }
        });
        lstTelefones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstTelefonesKeyReleased(evt);
            }
        });
        scrpTelefones.setViewportView(lstTelefones);

        getContentPane().add(scrpTelefones, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 510, 351, 210));

        edtTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtTipoTelefone.setText("jTextField1");
        getContentPane().add(edtTipoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 340, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tipos de Telefones");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        lblAddTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTipoTelefone.setText("+");
        lblAddTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddTipoTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblAddTipoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 490, -1, -1));

        lblDelTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTipoTelefone.setText("-");
        lblDelTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDelTipoTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblDelTipoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 490, -1, -1));

        lblEditTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTipoTelefone.setText("Edit");
        lblEditTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditTipoTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblEditTipoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Telefones");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 490, -1, -1));

        lblAddTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTelefone.setText("+");
        lblAddTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblAddTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 490, -1, -1));

        lblDelTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTelefone.setText("-");
        lblDelTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDelTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblDelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 490, -1, -1));

        lblEditTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTelefone.setText("Edit");
        lblEditTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditTelefoneMouseReleased(evt);
            }
        });
        getContentPane().add(lblEditTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstContatosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstContatosKeyReleased
        // TODO add your handling code here:
        loadContato();
    }//GEN-LAST:event_lstContatosKeyReleased

    private void lstContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseClicked
        // TODO add your handling code here:
        loadContato();
    }//GEN-LAST:event_lstContatosMouseClicked

    private void lstContatosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseReleased
        // TODO add your handling code here:
        loadContato();
    }//GEN-LAST:event_lstContatosMouseReleased

    private void lstContatosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseDragged
        // TODO add your handling code here:
        loadContato();
    }//GEN-LAST:event_lstContatosMouseDragged

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        lblMensagem.setText("Confirma a deleção do contato?");
        btnOK.setEnabled(true);
        btnCancel.setEnabled(true);
        comando = "DELETE";
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        btnOK.setEnabled(true);
        btnCancel.setEnabled(true);
        comando = "INSERT";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        switch (comando) {
            case "INSERT":
                insereContato();
                break;
            case "DELETE":
                deletaContato();
                break;
            case "UPDATE":
                atualizaContato();
                break;
            case "INSERTADDRESS":
                insereEndereco();
                break;
            case "DELETEADDRESS":
                deletaEndereco();
                break;
            case "UPDATEADDRESS":
                atualizaEndereco();
                break;
            case "INSERTADDRESSTYPE":
                insereTipoEndereco();
                break;
            case "DELETEADDRESSTYPE":
                deletaTipoEndereco();
                break;
            case "UPDATEADDRESSTYPE":
                atualizaEndereco();
                break;
            case "INSERTPHONE":
                // insereTelefone();
                break;
            case "DELETEPHONE":
                // deletaTelefone();
                break;
            case "UPDATEPHONE":
                // atualizaTelefone();
                break;
            case "INSERTPHONETYPE":
                insereTipoTelefone();
                break;
            case "DELETEPHONETYPEPHONE":
                deletaTipoTelefone();
                break;
            case "UPDATEPHONETYPE":
                // atualizaTelefone();
                break;

        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void edtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtNomeKeyReleased

    private void edtSobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSobrenomeKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtSobrenomeKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        btnCancel.setEnabled(false);
        btnOK.setEnabled(false);
        comando = "";
        lblMensagem.setText("");
        loadContato();
        scrpEnderecos.setLocation(300, 170);
        scrpEnderecos.setSize(340, 305);
        scrpTiposTelefones.setLocation(300, 510);
        scrpTiposTelefones.setSize(340, 210);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void lstEnderecosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstEnderecosKeyReleased
        // TODO add your handling code here:
        loadEndereco();
    }//GEN-LAST:event_lstEnderecosKeyReleased

    private void lstEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEnderecosMouseClicked
        // TODO add your handling code here:
        loadEndereco();
    }//GEN-LAST:event_lstEnderecosMouseClicked

    private void lstEnderecosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEnderecosMouseDragged
        // TODO add your handling code here:
        loadEndereco();
    }//GEN-LAST:event_lstEnderecosMouseDragged

    private void lstEnderecosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEnderecosMouseReleased
        // TODO add your handling code here:
        loadEndereco();
    }//GEN-LAST:event_lstEnderecosMouseReleased

    private void btnAddAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAddressActionPerformed
        // TODO add your handling code here:
        comando = "INSERTADDRESS";
        edtEndereco.setText("");
        edtBairro.setText("");
        edtCidade.setText("");
        edtEstado.setText("");
        edtPais.setText("");
        edtCEP.setText("");
        lstEnderecos.clearSelection();
        loadListaTipoEndereco();
    }//GEN-LAST:event_btnAddAddressActionPerformed

    private void edtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEnderecoKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtEnderecoKeyReleased

    private void btnDelAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAddrActionPerformed
        // TODO add your handling code here:
        lblMensagem.setText("Confirma a deleção do endereco?");
        btnOK.setEnabled(true);
        btnCancel.setEnabled(true);
        comando = "DELETEADDRESS";
    }//GEN-LAST:event_btnDelAddrActionPerformed

    private void edtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBairroKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtBairroKeyReleased

    private void edtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCidadeKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtCidadeKeyReleased

    private void edtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEstadoKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtEstadoKeyReleased

    private void edtPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPaisKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtPaisKeyReleased

    private void edtCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCEPKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtCEPKeyReleased

    private void lblDelTipoEnderecoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoEnderecoMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            loadListaTipoEndereco();
            lblMensagem.setText("Selecione o Tipo de Endereco, para deletar!");
            comando = "DELETEADDRESSTYPE";
            atualizaBotao();
        }

    }//GEN-LAST:event_lblDelTipoEnderecoMouseReleased

    private void lblEditTipoEnderecoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTipoEnderecoMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            if (lstEnderecos.getSelectedIndex() != -1) {
                loadListaTipoEndereco();
                comando = "UPDATEADDRESSTYPE";
                atualizaBotao();
            } else {
                lblMensagem.setText("Contato não tem endereço!");
            }
        }

    }//GEN-LAST:event_lblEditTipoEnderecoMouseReleased

    private void lblAddTipoEnderecoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoEnderecoMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            comando = "INSERTADDRESSTYPE";
            edtTipoEndereco.setText("");
            scrpEnderecos.setSize(340, 272);
            scrpEnderecos.setLocation(300, 200);
            btnOK.setEnabled(true);
            btnCancel.setEnabled(true);
        }
    }//GEN-LAST:event_lblAddTipoEnderecoMouseReleased

    private void lblAddTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoTelefoneMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            comando = "INSERTPHONETYPE";
            edtTipoTelefone.setText("");
            scrpTiposTelefones.setSize(340, 177);
            scrpTiposTelefones.setLocation(300, 540);
            btnOK.setEnabled(true);
            btnCancel.setEnabled(true);
        }
    }//GEN-LAST:event_lblAddTipoTelefoneMouseReleased

    private void lblDelTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoTelefoneMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            loadListaTipoTelefone();
            lblMensagem.setText("Selecione o Tipo de Telefone, para deletar!");
            comando = "DELETEPHONETYPEPHONE";
            atualizaBotao();
        }
    }//GEN-LAST:event_lblDelTipoTelefoneMouseReleased

    private void lblEditTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTipoTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditTipoTelefoneMouseReleased

    private void lblAddTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddTelefoneMouseReleased

    private void lblDelTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDelTelefoneMouseReleased

    private void lblEditTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditTelefoneMouseReleased

    private void lstTiposTelefonesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstTiposTelefonesKeyReleased
        // TODO add your handling code here:
        listSyncTelefone();
    }//GEN-LAST:event_lstTiposTelefonesKeyReleased

    private void lstTiposTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseClicked
        // TODO add your handling code here:
        listSyncTelefone();
    }//GEN-LAST:event_lstTiposTelefonesMouseClicked

    private void lstTiposTelefonesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseDragged
        // TODO add your handling code here:
        listSyncTelefone();
    }//GEN-LAST:event_lstTiposTelefonesMouseDragged

    private void lstTiposTelefonesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseReleased
        // TODO add your handling code here:
        listSyncTelefone();
    }//GEN-LAST:event_lstTiposTelefonesMouseReleased

    private void lstTelefonesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstTelefonesKeyReleased
        // TODO add your handling code here:
        listSyncTipoTelefone();
    }//GEN-LAST:event_lstTelefonesKeyReleased

    private void lstTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseClicked
        // TODO add your handling code here:
        listSyncTipoTelefone();
    }//GEN-LAST:event_lstTelefonesMouseClicked

    private void lstTelefonesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseDragged
        // TODO add your handling code here:
        listSyncTipoTelefone();
    }//GEN-LAST:event_lstTelefonesMouseDragged

    private void lstTelefonesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseReleased
        // TODO add your handling code here:
        listSyncTipoTelefone();
    }//GEN-LAST:event_lstTelefonesMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaContatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddAddress;
    private javax.swing.JButton btnAddPhone;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelAddr;
    private javax.swing.JButton btnDelPhone;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCEP;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPais;
    private javax.swing.JTextField edtSobrenome;
    private javax.swing.JTextField edtTipoEndereco;
    private javax.swing.JTextField edtTipoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddTelefone;
    private javax.swing.JLabel lblAddTipoEndereco;
    private javax.swing.JLabel lblAddTipoTelefone;
    private javax.swing.JLabel lblDelTelefone;
    private javax.swing.JLabel lblDelTipoEndereco;
    private javax.swing.JLabel lblDelTipoTelefone;
    private javax.swing.JLabel lblEditTelefone;
    private javax.swing.JLabel lblEditTipoEndereco;
    private javax.swing.JLabel lblEditTipoTelefone;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JList<String> lstContatos;
    private javax.swing.JList<String> lstEnderecos;
    private javax.swing.JList<String> lstTelefones;
    private javax.swing.JList<String> lstTiposTelefones;
    private javax.swing.JScrollPane scrpEnderecos;
    private javax.swing.JScrollPane scrpTelefones;
    private javax.swing.JScrollPane scrpTiposTelefones;
    // End of variables declaration//GEN-END:variables

    private static String comando = "";
    private static List<Integer> contatosIndice = new ArrayList<>();
    private static List<Integer> enderecosIndice = new ArrayList<>();
    private static List<Integer> tipoEnderecosIndice = new ArrayList<>();
    private static List<Integer> telefonesIndice = new ArrayList<>();
    private static List<Integer> tipoTelefonesIndice = new ArrayList<>();
    private static boolean temEndereco = false;
    private static boolean temTelefone = false;
    private static Endereco objEndereco = new Endereco();

    private void loadList() {
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = ContatoCtrl.pesquisa();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstContatos.setSelectedIndex(0);
        loadContato();
    }

    public static String[] pesquisa() {
        ArrayList<String> nomesSobrenomes = new ArrayList<String>();
        contatosIndice.clear();
        int count = 0;
        for (Contato contato : ContatoCtrl.pesquisaObj()) {
            nomesSobrenomes.add(contato.getNome() + " " + contato.getSobrenome());
            contatosIndice.add(contato.getIdContato());
            count++;
        }
        String[] retorno = nomesSobrenomes.toArray(new String[nomesSobrenomes.size()]);
        return retorno;
    }

    private void loadList2() {
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = pesquisa();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstContatos.setSelectedIndex(0);
        loadContato();
    }

    private void loadListEndereco() {
        if (temEndereco) {
            lstEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = ContatoCtrl.pesquisaTipoEndereco(tipoEnderecosIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstEnderecos.setSelectedIndex(0);
            Endereco endereco = new Endereco();
            endereco = EnderecoDao.buscaID(enderecosIndice.get(0));
            edtEndereco.setText(endereco.getEndereco());
            edtBairro.setText(endereco.getBairro());
            edtCidade.setText(endereco.getCidade());
            edtEstado.setText(endereco.getEstado());
            edtPais.setText(endereco.getPais());
            edtCEP.setText(endereco.getCep());
            objEndereco = endereco;
        } else {
            lstEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });

        }
    }

    private void loadListTelefone() {
        if (temTelefone) {
            lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = TelefoneCtrl.listaTelefones(telefonesIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTelefones.setSelectedIndex(0);
            lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = TipoTelefoneCtrl.listaTipoTelefones(tipoTelefonesIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTiposTelefones.setSelectedIndex(0);

        } else {
            lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });

        }
    }

    private void loadTipoTelefonesIndice() {
    }

    private void loadListaTipoTelefone() {
        tipoTelefonesIndice = TipoTelefoneCtrl.indice();
        lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TipoTelefoneCtrl.lista();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private String[] novaListaTipoEndereco() {
        List<TipoEndereco> tipoEndereco = TipoEnderecoDao.lista();
        List<String> listaTipoEndereco = new ArrayList<>();
        tipoEnderecosIndice.clear();
        for (TipoEndereco tipoEndereco1 : tipoEndereco) {
            tipoEnderecosIndice.add(tipoEndereco1.getIdTipoEndereco());
            listaTipoEndereco.add(tipoEndereco1.getTipoEndereco());
        }
        String[] retorno = listaTipoEndereco.toArray(new String[listaTipoEndereco.size()]);

        return retorno;
    }

    private void loadListaTipoEndereco() {
        lstEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = novaListaTipoEndereco();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void loadEndereco() {
        if (lstEnderecos.getSelectedIndex() != -1) {
            lblMensagem.setText("");
        }
        if (temEndereco
                && !comando.equals("INSERTADDRESS")
                && !comando.equals("DELETEADDRESSTYPE")
                && !comando.equals("UPDATEADDRESSTYPE")) {
            Endereco endereco = new Endereco();
            try {
                endereco = EnderecoDao.buscaID(enderecosIndice.get(lstEnderecos.getSelectedIndex()));

            } catch (Exception e) {
                System.out.println("Parei");
            }
            edtEndereco.setText(endereco.getEndereco());
            edtBairro.setText(endereco.getBairro());
            edtCidade.setText(endereco.getCidade());
            edtEstado.setText(endereco.getEstado());
            edtPais.setText(endereco.getPais());
            edtCEP.setText(endereco.getCep());
            objEndereco = endereco;
        }
    }

    private void loadContato() {
        for (Contato contato
                : ContatoCtrl.carregaContato(
                        StrNormalize.removeAcentos1(
                                (lstContatos.getSelectedIndex() == -1
                                ? ""
                                : lstContatos.getSelectedValue())
                        )
                                .toLowerCase()
                )) {
            edtNome.setText(contato.getNome());
            edtSobrenome.setText(contato.getSobrenome());
            temEndereco = false;
            temTelefone = false;
            enderecosIndice.clear();
            tipoEnderecosIndice.clear();
            telefonesIndice.clear();
            tipoTelefonesIndice.clear();
            for (Endereco endereco : ContatoCtrl.pesquisaEnderecoIdContato(contato.getIdContato())) {
//                edtEndereco.setText(endereco.getEndereco());
//                edtBairro.setText(endereco.getBairro());
//                edtCidade.setText(endereco.getCidade());
//                edtEstado.setText(endereco.getEstado());
//                edtPais.setText(endereco.getPais());
//                edtCEP.setText(endereco.getCep());
                enderecosIndice.add(endereco.getIdEndereco());
                tipoEnderecosIndice.add(endereco.getIdTipoEndereco());
                temEndereco = true;
            }
            if (!temEndereco) {
                edtEndereco.setText("");
                edtBairro.setText("");
                edtCidade.setText("");
                edtEstado.setText("");
                edtPais.setText("");
                edtCEP.setText("");
            }
            for (Telefone telefone : TelefoneDao.listaIDContato(contato.getIdContato())) {
                telefonesIndice.add(telefone.getIdTelefone());
                tipoTelefonesIndice.add(telefone.getIdTipoTelefone());
                temTelefone = true;
            }
            loadListEndereco();
            loadListTelefone();
        }
    }

    private void limpaCampos() {

        edtNome.setText("");
        edtSobrenome.setText("");
    }

    private void insereContato() {
        if (comando.equals("INSERT")) {
            if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
                ContatoCtrl.insere(edtNome.getText(), edtSobrenome.getText());
                limpaCampos();
                loadList2();
                comando = "";
            }
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
        }
    }

    private void atualizaContato() {
        if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
            ContatoCtrl.altera(
                    contatosIndice.get(lstContatos.getSelectedIndex()),
                    edtNome.getText(),
                    edtSobrenome.getText());
            limpaCampos();
            loadList2();
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            comando = "";
        }
    }

    private void atualizaContatoGeral() {
        if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
            ContatoCtrl.alteraGeral(
                    lstContatos.getSelectedValue(),
                    edtNome.getText(),
                    edtSobrenome.getText());
            limpaCampos();
            loadList2();
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            comando = "";
        }
    }

    private void deletaContato() {
        if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
            ContatoCtrl.deleta(contatosIndice.get(lstContatos.getSelectedIndex()));
            limpaCampos();
            loadList2();
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            comando = "";
        }
    }

    private void insereEndereco() {
        if (comando.equals("INSERTADDRESS") && lstEnderecos.getSelectedIndex() != -1) {
            if (!edtEndereco.getText().isEmpty()) {
                Endereco endereco = new Endereco();
                endereco.setEndereco(edtEndereco.getText());
                endereco.setBairro(edtBairro.getText());
                endereco.setCidade(edtCidade.getText());
                endereco.setEstado(edtEstado.getText());
                endereco.setCep(edtCEP.getText());
                endereco.setPais(edtPais.getText());
                endereco.setIdContato(contatosIndice.get(lstContatos.getSelectedIndex()));
                endereco.setIdTipoEndereco(tipoEnderecosIndice.get(lstEnderecos.getSelectedIndex()));
                EnderecoDao.insere(endereco);
                comando = "";
                btnOK.setEnabled(false);
                btnCancel.setEnabled(false);
                loadContato();
            }
        } else if (lstEnderecos.getSelectedIndex() == -1) {
            lblMensagem.setText("Selecione um tipo de endereço.");
        }

    }

    private void deletaEndereco() {
        boolean retorno;
        retorno = EnderecoDao.deleta(enderecosIndice.get(lstEnderecos.getSelectedIndex()));
        loadContato();
        lblMensagem.setText("");
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);

    }

    private void atualizaEndereco() {
        if (temEndereco) {
            if (!edtEndereco.getText().isEmpty()) {
                Endereco endereco = new Endereco();
                endereco.setIdEndereco(objEndereco.getIdEndereco());
                endereco.setEndereco(edtEndereco.getText());
                endereco.setBairro(edtBairro.getText());
                endereco.setCidade(edtCidade.getText());
                endereco.setEstado(edtEstado.getText());
                endereco.setCep(edtCEP.getText());
                endereco.setPais(edtPais.getText());
                endereco.setIdContato(contatosIndice.get(lstContatos.getSelectedIndex()));
                endereco.setIdTipoEndereco(tipoEnderecosIndice.get(lstEnderecos.getSelectedIndex()));
                EnderecoDao.altera(endereco);
                comando = "";
                btnOK.setEnabled(false);
                btnCancel.setEnabled(false);
                loadContato();
            }
        } else {
            comando = "INSERTADDRESS";
            loadListaTipoEndereco();
            lblMensagem.setText("Selecione um tipo de endereço.");
        }

    }

    private void insereTipoEndereco() {
        TipoEndereco tipoEndereco = new TipoEndereco();
        tipoEndereco.setTipoEndereco(edtTipoEndereco.getText());
        if (!TipoEnderecoDao.insere(tipoEndereco)) {
            lblMensagem.setText("Tipo de Endereço não cadastrado!");
        }
        scrpEnderecos.setLocation(300, 170);
        scrpEnderecos.setSize(340, 230);
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        comando = "";
    }

    private void deletaTipoEndereco() {
        if (!EnderecoDao.buscaIDTipoEndereco(tipoEnderecosIndice.get(lstEnderecos.getSelectedIndex()))) {
            TipoEnderecoDao.deleta((tipoEnderecosIndice.get(lstEnderecos.getSelectedIndex())));
        } else {
            lblMensagem.setText("Tipo de Endereço em uso, não pode ser deletado!");
        }
        comando = "";
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        loadContato();
    }

    private void insereTipoTelefone() {
        TipoTelefone tipoTelefone = new TipoTelefone();
        tipoTelefone.setTipoTelefone(edtTipoTelefone.getText());
        if (!TipoTelefoneDao.insere(tipoTelefone)) {
            lblMensagem.setText("Tipo de Telefone não cadastrado!");
        }
        scrpTiposTelefones.setLocation(300, 510);
        scrpTiposTelefones.setSize(340, 210);
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        comando = "";
    }

    private void deletaTipoTelefone() {
        System.out.println("Tipo selecionado = " + lstTiposTelefones.getSelectedIndex());

        if (!TelefoneDao.buscaIDTipoTipo(tipoTelefonesIndice.get(lstTiposTelefones.getSelectedIndex()))) {
            TipoTelefoneDao.deleta((tipoTelefonesIndice.get(lstTiposTelefones.getSelectedIndex())));
        } else {
            lblMensagem.setText("Tipo de Telefone em uso, não pode ser deletado!");
        }
        comando = "";
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        loadContato();

    }

    private void atualizaBotao() {
        if ((lstContatos.getSelectedIndex() == -1
                ? false
                : !lstContatos.getSelectedValue().equals(edtNome.getText() + " " + edtSobrenome.getText()))) {
            if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
                if (comando.equals("")) {
                    comando = "UPDATE";
                    btnOK.setEnabled(true);
                    btnCancel.setEnabled(true);
                }
            }
        } else if (comando.equals("UPDATE")) {
            comando = "";
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
        }

        if (!edtEndereco.getText().equals(objEndereco.getEndereco())
                || !edtBairro.getText().equals(objEndereco.getBairro())
                || !edtCidade.getText().equals(objEndereco.getCidade())
                || !edtEstado.getText().equals(objEndereco.getEstado())
                || !edtPais.getText().equals(objEndereco.getPais())
                || !edtCEP.getText().equals(objEndereco.getCep())) {
            if (!edtEndereco.getText().isEmpty()) {
                if (comando.equals("")) {
                    comando = "UPDATEADDRESS";
                    btnOK.setEnabled(true);
                    btnCancel.setEnabled(true);
                }
            }
        } else if (comando.equals("UPDATEADDRESS")) {
            comando = "";
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
        }
        if (comando.equals("UPDATEADDRESSTYPE")
                || comando.equals("DELETEADDRESSTYPE")
                || comando.equals("DELETEPHONETYPEPHONE")) {
            btnOK.setEnabled(true);
            btnCancel.setEnabled(true);
        }
    }

    private void listSyncTipoTelefone() {
        if (comando.equals("")) {
            lstTiposTelefones.setSelectedIndex(lstTelefones.getSelectedIndex());
        }
    }

    private void listSyncTelefone() {
        if (comando.equals("")) {
            lstTelefones.setSelectedIndex(lstTiposTelefones.getSelectedIndex());
        }
    }

}
