package com.adrianocodenow.contatos2022.view;

import com.adrianocodenow.contatos2022.controller.ContatoCtrl;
import com.adrianocodenow.contatos2022.controller.TelefoneCtrl;
import com.adrianocodenow.contatos2022.controller.TipoTelefoneCtrl;
import com.adrianocodenow.contatos2022.dao.ContatosDao;
import com.adrianocodenow.contatos2022.dao.CriaTabelas;
import com.adrianocodenow.contatos2022.dao.EnderecoDao;
import com.adrianocodenow.contatos2022.dao.TelefoneDao;
import com.adrianocodenow.contatos2022.dao.TipoEnderecoDao;
import com.adrianocodenow.contatos2022.dao.TipoTelefoneDao;
import com.adrianocodenow.contatos2022.model.Contato;
import com.adrianocodenow.contatos2022.model.Endereco;
import com.adrianocodenow.contatos2022.model.TipoEndereco;
import com.adrianocodenow.contatos2022.model.TipoTelefone;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author apereira
 */
public class ListaContatos extends javax.swing.JFrame {

    private Evento evento;

    private Contato contato;
    private List<Contato> listContato;

    private Endereco endereco = new Endereco();
    private List<Endereco> listEndereco = new ArrayList<>();
    // TIPO DE ENDEREÇO
    private TipoEndereco tipoEndereco;
    private List<TipoEndereco> listTipoEndereco;

    // TIPO DE TELEFONE
    private TipoTelefone tipoTelefone;
    private TipoTelefoneDao tipoTelefoneDao = new TipoTelefoneDao();

    /**
     * Creates new form ListaContatos
     */
    public ListaContatos() {
        //CriaTabelas.criaBancoDeDados();
        initComponents();
        lblMensagem.setText("");
        desativaCampos();
        limpaTodosCampos();

        // CONTATO
        loadContato();

        // TIPO ENDEREÇO
        //loadTipoEnderco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstContatos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEditTipoEndereco = new javax.swing.JLabel();
        lblDelTipoEndereco = new javax.swing.JLabel();
        lblAddTipoEndereco = new javax.swing.JLabel();
        edtTipoEndereco = new javax.swing.JTextField();
        scrpTiposEnderecos = new javax.swing.JScrollPane();
        lstTiposEnderecos = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblEditTipoTelefone = new javax.swing.JLabel();
        lblDelTipoTelefone = new javax.swing.JLabel();
        lblAddTipoTelefone = new javax.swing.JLabel();
        edtTipoTelefone = new javax.swing.JTextField();
        scrpTiposTelefones = new javax.swing.JScrollPane();
        lstTiposTelefones = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtSobrenome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edtCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edtEstado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtPais = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtCEP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblEditTelefone = new javax.swing.JLabel();
        lblDelTelefone = new javax.swing.JLabel();
        lblAddTelefone = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        scrpTelefones = new javax.swing.JScrollPane();
        lstTelefones = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnAddAddress = new javax.swing.JButton();
        btnDelAddr = new javax.swing.JButton();
        btnAddPhone = new javax.swing.JButton();
        btnDelPhone = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Contatos");
        jLabel2.setOpaque(true);

        lstContatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstContatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstContatosMouseDragged(evt);
            }
        });
        lstContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstContatosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstContatosMouseReleased(evt);
            }
        });
        lstContatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstContatosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstContatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        jLabel3.setOpaque(true);

        edtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtNome.setText("jTextField1");
        edtNome.setMaximumSize(new java.awt.Dimension(351, 30));
        edtNome.setMinimumSize(new java.awt.Dimension(351, 30));
        edtNome.setNextFocusableComponent(edtSobrenome);
        edtNome.setPreferredSize(new java.awt.Dimension(330, 30));
        edtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtNomeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tipos de Endereço");

        lblEditTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTipoEndereco.setText("Edit");
        lblEditTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditTipoEnderecoMouseClicked(evt);
            }
        });

        lblDelTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTipoEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelTipoEndereco.setText("-");
        lblDelTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelTipoEnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDelTipoEnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDelTipoEnderecoMouseExited(evt);
            }
        });

        lblAddTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTipoEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddTipoEndereco.setText("+");
        lblAddTipoEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddTipoEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddTipoEnderecoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddTipoEnderecoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddTipoEnderecoMouseExited(evt);
            }
        });

        edtTipoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtTipoEndereco.setText("jTextField1");

        scrpTiposEnderecos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstTiposEnderecos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTiposEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTiposEnderecosMouseClicked(evt);
            }
        });
        scrpTiposEnderecos.setViewportView(lstTiposEnderecos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(edtTipoEndereco)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDelTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditTipoEndereco))
                    .addComponent(scrpTiposEnderecos))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEditTipoEndereco)
                    .addComponent(lblDelTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpTiposEnderecos)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Tipos de Telefones");

        lblEditTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTipoTelefone.setText("Edit");
        lblEditTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditTipoTelefoneMouseReleased(evt);
            }
        });

        lblDelTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTipoTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelTipoTelefone.setText("-");
        lblDelTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDelTipoTelefoneMouseReleased(evt);
            }
        });

        lblAddTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTipoTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddTipoTelefone.setText("+");
        lblAddTipoTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddTipoTelefoneMouseReleased(evt);
            }
        });

        edtTipoTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtTipoTelefone.setText("jTextField1");

        scrpTiposTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstTiposTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTiposTelefones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseDragged(evt);
            }
        });
        lstTiposTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstTiposTelefonesMouseReleased(evt);
            }
        });
        lstTiposTelefones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstTiposTelefonesKeyReleased(evt);
            }
        });
        scrpTiposTelefones.setViewportView(lstTiposTelefones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTipoTelefone)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDelTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditTipoTelefone))
                    .addComponent(scrpTiposTelefones))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblEditTipoTelefone)
                    .addComponent(lblDelTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpTiposTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Sobrenome");
        jLabel1.setOpaque(true);

        edtSobrenome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtSobrenome.setText("jTextField1");
        edtSobrenome.setMaximumSize(new java.awt.Dimension(351, 30));
        edtSobrenome.setMinimumSize(new java.awt.Dimension(351, 30));
        edtSobrenome.setPreferredSize(new java.awt.Dimension(330, 30));
        edtSobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtSobrenomeKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Endereço");

        edtEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtEndereco.setText("jTextField1");
        edtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtEnderecoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Bairro");

        edtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtBairro.setText("jTextField2");
        edtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtBairroKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Cidade");

        edtCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtCidade.setText("jTextField2");
        edtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCidadeKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Estado");

        edtEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtEstado.setText("jTextField2");
        edtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtEstadoKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("País");

        edtPais.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtPais.setText("jTextField2");
        edtPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtPaisKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("CEP");

        edtCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtCEP.setText("jTextField2");
        edtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edtCEPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtEndereco)
                    .addComponent(edtBairro)
                    .addComponent(edtEstado)
                    .addComponent(edtCidade)
                    .addComponent(edtPais)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(edtCEP))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(edtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Telefones");

        lblEditTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEditTelefone.setText("Edit");
        lblEditTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEditTelefoneMouseReleased(evt);
            }
        });

        lblDelTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelTelefone.setText("-");
        lblDelTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblDelTelefoneMouseReleased(evt);
            }
        });

        lblAddTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAddTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddTelefone.setText("+");
        lblAddTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAddTelefoneMouseReleased(evt);
            }
        });

        edtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtTelefone.setText("jTextField1");

        lstTelefones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTelefones.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseDragged(evt);
            }
        });
        lstTelefones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstTelefonesMouseReleased(evt);
            }
        });
        lstTelefones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstTelefonesKeyReleased(evt);
            }
        });
        scrpTelefones.setViewportView(lstTelefones);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrpTelefones)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditTelefone)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblEditTelefone)
                    .addComponent(lblDelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 64, 64));

        btnDel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDel.setText("-");
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelMouseExited(evt);
            }
        });
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel6.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 64, 64));

        btnAddAddress.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnAddAddress.setText("+ End");
        btnAddAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddAddressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddAddressMouseExited(evt);
            }
        });
        btnAddAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAddressActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 64, 64));

        btnDelAddr.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnDelAddr.setText("- End");
        btnDelAddr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelAddr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelAddrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelAddrMouseExited(evt);
            }
        });
        btnDelAddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAddrActionPerformed(evt);
            }
        });
        jPanel6.add(btnDelAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 64, 64));

        btnAddPhone.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnAddPhone.setText("+ Tel");
        btnAddPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPhoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddPhoneMouseExited(evt);
            }
        });
        jPanel6.add(btnAddPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 64, 64));

        btnDelPhone.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnDelPhone.setText("- Tel");
        btnDelPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelPhoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelPhoneMouseExited(evt);
            }
        });
        jPanel6.add(btnDelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 64, 64));

        btnSearch.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSearch.setText("?");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        jPanel6.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 64, 64));

        btnCancel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancel.setText("X");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setEnabled(false);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel6.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 64, 64));

        btnOK.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnOK.setText("OK");
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOK.setEnabled(false);
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOKMouseExited(evt);
            }
        });
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel6.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 12, 64, 64));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("MENSAGEM");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 11, -1, -1));

        lblMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMensagem.setText("LINHA DE MENSAGEM");
        jPanel6.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 28, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstContatosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstContatosKeyReleased
        if (listContato != null && !listContato.isEmpty()) {
            contato = listContato.get(lstContatos.getSelectedIndex());

            edtNome.setText(contato.getNome());
            edtSobrenome.setText(contato.getSobrenome());

            evento = Evento.UPDATECONTATO;
        }
    }//GEN-LAST:event_lstContatosKeyReleased

    private void lstContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseClicked
        if (listContato.size()>0) {

            contato = listContato.get(lstContatos.getSelectedIndex());

            ativaNomeSobrenome();
            edtNome.setText(contato.getNome());
            edtSobrenome.setText(contato.getSobrenome());

            loadTipoEnderco();
        }
    }//GEN-LAST:event_lstContatosMouseClicked

    private void lstContatosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseReleased
        evento = Evento.CLKCONTATO;
    }//GEN-LAST:event_lstContatosMouseReleased

    private void lstContatosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContatosMouseDragged
        evento = Evento.CLKCONTATO;
    }//GEN-LAST:event_lstContatosMouseDragged

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        ativaOKCancel(Evento.DELCONTATO, "Confirma a deleção do contato?");
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ativaNomeSobrenome();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        switch (evento) {
            case ADDCONTATO:
                insereContato();
                break;
            case UPDATECONTATO:
                atualizaContato();
                loadContato();
                break;
            case DELCONTATO:
                deletaContato();
                break;
            case ADDENDERECO:
                insereEndereco();
                break;
            case UPDATEENDERECO:
                atualizaEndereco();
                break;
            case ADDTIPOENDERECO:
                insereTipoEndereco();
                break;
            case UPDATETIPOENDERECO:
                if (tipoEndereco != null && edtTipoEndereco.getText().length() > 3) {
                    btnOK.setEnabled(false);
                    btnCancel.setEnabled(false);
                    edtTipoEndereco.setVisible(false);
                    lblMensagem.setText("");
                    edtNome.requestFocus();

                    tipoEndereco.setTipoEndereco(edtTipoEndereco.getText().trim());
                    if (TipoEnderecoDao.altera(tipoEndereco)) {
                        JOptionPane.showMessageDialog(rootPane, "Tipo de endereço " + tipoEndereco.getTipoEndereco() + " alterado com sucesso!!!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao alterar o tipo de endereço " + tipoEndereco.getTipoEndereco() + "!!!");
                    }
                    loadListaTiposEnderecos();
                    edtTipoEndereco.setText("");
                    tipoEndereco = null;
                }
                break;
        }
        desativaOKCancel();
        desativaNomeSobrenome();
    }//GEN-LAST:event_btnOKActionPerformed

    private void edtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeKeyReleased
        isUpdateContato();
    }//GEN-LAST:event_edtNomeKeyReleased

    private void edtSobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSobrenomeKeyReleased
        isUpdateContato();
    }//GEN-LAST:event_edtSobrenomeKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lstTiposEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposEnderecosMouseClicked
        if (!listTipoEndereco.isEmpty()) {
            tipoEndereco = listTipoEndereco.get(lstTiposEnderecos.getSelectedIndex());
            listEndereco = EnderecoDao.buscaContato(contato, tipoEndereco);
            loadEndereco();
        }
    }//GEN-LAST:event_lstTiposEnderecosMouseClicked

    private void btnAddAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAddressActionPerformed
        if (contato == null) {
            JOptionPane.showMessageDialog(rootPane, "Escolha um contato na lista!");
            return;
        }
        if (tipoEndereco == null) {
            JOptionPane.showMessageDialog(rootPane, "Escolha um tipo de endereço na lista!");
            return;
        }
        ativaEndereco();
    }//GEN-LAST:event_btnAddAddressActionPerformed

    private void edtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEnderecoKeyReleased
        if (listEndereco.isEmpty()) {
            ativaOKCancel(Evento.ADDENDERECO, "Clique OK para adicionar endereço!");
        } else {
            ativaOKCancel(Evento.UPDATEENDERECO, "Clique OK para atualizar endereço!");
        }
    }//GEN-LAST:event_edtEnderecoKeyReleased

    private void btnDelAddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAddrActionPerformed
        // TODO add your handling code here:
        ativaOKCancel(Evento.DELENDERECO, "Confirma a deleção do endereco?");
    }//GEN-LAST:event_btnDelAddrActionPerformed

    private void edtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtBairroKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtBairroKeyReleased

    private void edtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCidadeKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtCidadeKeyReleased

    private void edtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEstadoKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtEstadoKeyReleased

    private void edtPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPaisKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtPaisKeyReleased

    private void edtCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCEPKeyReleased
        // TODO add your handling code here:
        atualizaBotao();
    }//GEN-LAST:event_edtCEPKeyReleased

    private void lblAddTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoTelefoneMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            edtTipoTelefone.setText("");
            edtTipoTelefone.setEnabled(true);
            edtTipoTelefone.requestFocus();
            scrpTiposTelefones.setSize(340, 177);
            scrpTiposTelefones.setLocation(300, 540);
            loadListaTiposTelefones();
            ativaOKCancel(Evento.ADDTIPOTELEFONE, "");

        }
    }//GEN-LAST:event_lblAddTipoTelefoneMouseReleased

    private void lblDelTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoTelefoneMouseReleased
        // TODO add your handling code here:
        if (comando.equals("")) {
            loadListaTiposTelefones();
            if (indexTiposTelefones != -1) {
                lstTiposTelefones.setSelectedIndex(indexTiposTelefones);
                ativaOKCancel(Evento.DELTIPOTELEFONE, "");
            } else {
                ativaOKCancel(Evento.DELTIPOTELEFONE, "Selecione o Tipo de Telefone, para deletar!");
            }
        }
    }//GEN-LAST:event_lblDelTipoTelefoneMouseReleased

    private void lblEditTipoTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTipoTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditTipoTelefoneMouseReleased

    private void lblAddTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAddTelefoneMouseReleased

    private void lblDelTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDelTelefoneMouseReleased

    private void lblEditTelefoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTelefoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditTelefoneMouseReleased

    private void lstTiposTelefonesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstTiposTelefonesKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTiposTelefonesKeyReleased

    private void lstTiposTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTiposTelefonesMouseClicked

    private void lstTiposTelefonesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTiposTelefonesMouseDragged

    private void lstTiposTelefonesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTiposTelefonesMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTiposTelefonesMouseReleased

    private void lstTelefonesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstTelefonesKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTelefonesKeyReleased

    private void lstTelefonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lstTelefonesMouseClicked

    private void lstTelefonesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTelefonesMouseDragged

    private void lstTelefonesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTelefonesMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lstTelefonesMouseReleased

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        isFocus(btnAdd, true);
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        isFocus(btnAdd, false);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseEntered
        isFocus(btnDel, true);
    }//GEN-LAST:event_btnDelMouseEntered

    private void btnDelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseExited
        isFocus(btnDel, false);
    }//GEN-LAST:event_btnDelMouseExited

    private void btnAddAddressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAddressMouseEntered
        isFocus(btnAddAddress, true);
    }//GEN-LAST:event_btnAddAddressMouseEntered

    private void btnAddAddressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAddressMouseExited
        isFocus(btnAddAddress, false);
    }//GEN-LAST:event_btnAddAddressMouseExited

    private void btnDelAddrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelAddrMouseEntered
        isFocus(btnDelAddr, true);
    }//GEN-LAST:event_btnDelAddrMouseEntered

    private void btnDelAddrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelAddrMouseExited
        isFocus(btnDelAddr, false);
    }//GEN-LAST:event_btnDelAddrMouseExited

    private void btnAddPhoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPhoneMouseEntered
        isFocus(btnAddPhone, true);
    }//GEN-LAST:event_btnAddPhoneMouseEntered

    private void btnAddPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPhoneMouseExited
        isFocus(btnAddPhone, false);
    }//GEN-LAST:event_btnAddPhoneMouseExited

    private void btnDelPhoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelPhoneMouseEntered
        isFocus(btnDelPhone, true);
    }//GEN-LAST:event_btnDelPhoneMouseEntered

    private void btnDelPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelPhoneMouseExited
        isFocus(btnDelPhone, false);
    }//GEN-LAST:event_btnDelPhoneMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        isFocus(btnSearch, true);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        isFocus(btnSearch, false);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        isFocus(btnCancel, true);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        isFocus(btnCancel, false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseEntered
        isFocus(btnOK, true);
    }//GEN-LAST:event_btnOKMouseEntered

    private void btnOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseExited
        isFocus(btnOK, false);
    }//GEN-LAST:event_btnOKMouseExited

    private void lblAddTipoEnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoEnderecoMouseExited
        isFocus(lblAddTipoEndereco, false);
    }//GEN-LAST:event_lblAddTipoEnderecoMouseExited

    private void lblAddTipoEnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoEnderecoMouseEntered
        isFocus(lblAddTipoEndereco, true);
    }//GEN-LAST:event_lblAddTipoEnderecoMouseEntered

    private void lblAddTipoEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTipoEnderecoMouseClicked
        ativaOKCancel(Evento.ADDTIPOENDERECO, "Adicionar tipo de endereço!");
        edtTipoEndereco.setVisible(true);
        edtTipoEndereco.requestFocus();
    }//GEN-LAST:event_lblAddTipoEnderecoMouseClicked

    private void lblDelTipoEnderecoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoEnderecoMouseEntered
        isFocus(lblAddTipoTelefone, true);
    }//GEN-LAST:event_lblDelTipoEnderecoMouseEntered

    private void lblDelTipoEnderecoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoEnderecoMouseExited
        isFocus(lblAddTipoTelefone, false);
    }//GEN-LAST:event_lblDelTipoEnderecoMouseExited

    private void lblDelTipoEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelTipoEnderecoMouseClicked
        if (tipoEndereco != null) {
            if (TipoEnderecoDao.deleta(tipoEndereco.getIdTipoEndereco())) {
                JOptionPane.showMessageDialog(rootPane, "Tipo de endereço " + tipoEndereco.getTipoEndereco() + " apagado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao apagar o tipo de endereço " + tipoEndereco.getTipoEndereco() + "!");
            }
            loadListaTiposEnderecos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Escolha na lista o tipo de endereço para apagar!");
        }
        tipoEndereco = null;
    }//GEN-LAST:event_lblDelTipoEnderecoMouseClicked

    private void lblEditTipoEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditTipoEnderecoMouseClicked
        if (tipoEndereco != null) {
            ativaOKCancel(Evento.UPDATETIPOENDERECO, "Alterar tipo de endereço");
            edtTipoEndereco.setVisible(true);
            edtTipoEndereco.setText(tipoEndereco.getTipoEndereco());
            edtTipoEndereco.requestFocus();
        }
    }//GEN-LAST:event_lblEditTipoEnderecoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaContatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddAddress;
    private javax.swing.JButton btnAddPhone;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelAddr;
    private javax.swing.JButton btnDelPhone;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCEP;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPais;
    private javax.swing.JTextField edtSobrenome;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JTextField edtTipoEndereco;
    private javax.swing.JTextField edtTipoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddTelefone;
    private javax.swing.JLabel lblAddTipoEndereco;
    private javax.swing.JLabel lblAddTipoTelefone;
    private javax.swing.JLabel lblDelTelefone;
    private javax.swing.JLabel lblDelTipoEndereco;
    private javax.swing.JLabel lblDelTipoTelefone;
    private javax.swing.JLabel lblEditTelefone;
    private javax.swing.JLabel lblEditTipoEndereco;
    private javax.swing.JLabel lblEditTipoTelefone;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JList<String> lstContatos;
    private javax.swing.JList<String> lstTelefones;
    private javax.swing.JList<String> lstTiposEnderecos;
    private javax.swing.JList<String> lstTiposTelefones;
    private javax.swing.JScrollPane scrpTelefones;
    private javax.swing.JScrollPane scrpTiposEnderecos;
    private javax.swing.JScrollPane scrpTiposTelefones;
    // End of variables declaration//GEN-END:variables

    private static String comando = "";
    private static List<Integer> contatosIndice = new ArrayList<>();
    private static List<Integer> enderecosIndice = new ArrayList<>();
    private static List<Integer> tiposEnderecosIndice = new ArrayList<>();
    private static List<Integer> telefonesIndice = new ArrayList<>();
    private static List<Integer> tiposTelefonesIndice = new ArrayList<>();
    private static boolean temContato = false;
    private static boolean temEndereco = false;
    private static boolean temTelefone = false;
    private static Integer indexTiposEnderecos = -1;
    private static Integer indexTiposTelefones = -1;
    private static Endereco objEndereco = new Endereco();

    private void isUpdateContato() {
        if (contato == null) {
            ativaOKCancel(Evento.ADDCONTATO, "Clique OK para adicionar contato!");
        }
        if (!contato.getNome().equalsIgnoreCase(edtNome.getText().trim())
                || !contato.getSobrenome().equalsIgnoreCase(edtSobrenome.getText().trim())) {
            ativaOKCancel(Evento.UPDATECONTATO, "Clique OK para atualizar contato!");
        }
    }

    private static enum Evento {
        ADDCONTATO, DELCONTATO, UPDATECONTATO,
        ADDENDERECO, DELENDERECO, UPDATEENDERECO,
        ADDTELEFONE, DELTELEFONE, UPDATETELEFONE,
        ADDTIPOENDERECO, DELTIPOENDERECO, UPDATETIPOENDERECO,
        ADDTIPOTELEFONE, DELTIPOTELEFONE, UPDATETIPOTELEFONE,
        CLKCONTATO, CLKTIPOENDERECO, CLKTIPOTELEFONE, CLKTELEFONE,
        NULL
    };

    private void ativaOKCancel(Evento evento, String mensagem) {
        lblMensagem.setText(mensagem);
        btnOK.setEnabled(true);
        btnCancel.setEnabled(true);
        this.evento = evento;
    }

    private void desativaOKCancel() {
        contato = null;
        tipoEndereco = null;
        endereco = null;

        lblMensagem.setText("");
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        this.evento = Evento.NULL;
    }

    private void cancel() {
        btnCancel.setEnabled(false);
        btnOK.setEnabled(false);
        comando = "";
        lblMensagem.setText("");
        indexTiposEnderecos = -1;
        indexTiposTelefones = -1;
        loadContato();
        scrpTiposEnderecos.setLocation(300, 170);
        scrpTiposEnderecos.setSize(340, 305);
        scrpTiposTelefones.setLocation(300, 510);
        scrpTiposTelefones.setSize(340, 210);
    }

    private void loadList() {
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = ContatoCtrl.pesquisa();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstContatos.setSelectedIndex(0);
        loadContato();
    }

    public static String[] pesquisa() {
        ArrayList<String> nomesSobrenomes = new ArrayList<String>();
        contatosIndice.clear();
        int count = 0;
        temContato = false;
        for (Contato contato : ContatoCtrl.pesquisaObj()) {
            nomesSobrenomes.add(contato.getNome() + " " + contato.getSobrenome());
            contatosIndice.add(contato.getIdContato());
            count++;
            temContato = true;
        }
        String[] retorno = nomesSobrenomes.toArray(new String[nomesSobrenomes.size()]);
        return retorno;
    }

    private void loadList2() {
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = pesquisa();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstContatos.setSelectedIndex(0);
        loadContato();
    }

    private void loadListEndereco() {
        if (temEndereco) {
            lstTiposEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = ContatoCtrl.pesquisaTipoEndereco(tiposEnderecosIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTiposEnderecos.setSelectedIndex(0);
            Endereco endereco = new Endereco();
            endereco = EnderecoDao.buscaID(enderecosIndice.get(0));
            edtEndereco.setText(endereco.getEndereco());
            edtBairro.setText(endereco.getBairro());
            edtCidade.setText(endereco.getCidade());
            edtEstado.setText(endereco.getEstado());
            edtPais.setText(endereco.getPais());
            edtCEP.setText(endereco.getCep());
            objEndereco = endereco;
        } else {
            loadListaTiposEnderecos();
        }
    }

    private void loadListTelefone() {
        if (temTelefone) {
            lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = TelefoneCtrl.listaTelefones(telefonesIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTelefones.setSelectedIndex(0);
            lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = TipoTelefoneCtrl.listaTipoTelefones(tiposTelefonesIndice);

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTiposTelefones.setSelectedIndex(0);

        } else {
            lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = {};

                public int getSize() {
                    return strings.length;
                }

                public String getElementAt(int i) {
                    return strings[i];
                }
            });
            loadListaTiposTelefones();
        }
    }

    private void loadTipoTelefonesIndice() {
    }

    private void loadListaTiposTelefones() {
        tiposTelefonesIndice = TipoTelefoneCtrl.indice();
        lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = TipoTelefoneCtrl.lista();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private String[] novaListaTipoEndereco() {
        List<TipoEndereco> tipoEndereco = TipoEnderecoDao.lista();
        listTipoEndereco = tipoEndereco;
        List<String> listaTipoEndereco = new ArrayList<>();
        tiposEnderecosIndice.clear();
        for (TipoEndereco tipoEndereco1 : tipoEndereco) {
            tiposEnderecosIndice.add(tipoEndereco1.getIdTipoEndereco());
            listaTipoEndereco.add(tipoEndereco1.getTipoEndereco());
        }
        String[] retorno = listaTipoEndereco.toArray(new String[listaTipoEndereco.size()]);

        return retorno;
    }

    private void loadListaTiposEnderecos() {
        lstTiposEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = novaListaTipoEndereco();

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void loadEndereco() {
        listEndereco = EnderecoDao.buscaContato(contato, tipoEndereco);
        if (listEndereco.size()>0) {
            ativaEndereco();            
            edtEndereco.setText(endereco.getEndereco());
            edtBairro.setText(endereco.getBairro());
            edtCidade.setText(endereco.getCidade());
            edtEstado.setText(endereco.getEstado());
            edtPais.setText(endereco.getPais());
            edtCEP.setText(endereco.getCep());
        }else{
            desativaEndereco();
        }
    }

    private void loadTipoEnderco() {
        listTipoEndereco = new ArrayList<>();
        if (contato != null && tipoEndereco != null) {
            listTipoEndereco = TipoEnderecoDao.pesquisaContato(contato, tipoEndereco);
        } else {
            listTipoEndereco = TipoEnderecoDao.pesquisaContato(contato);
        }
        if(listTipoEndereco.isEmpty()){
            ativaEndereco();
        }else{
            desativaEndereco();
        }
        lstTiposEnderecos.setModel(TipoEnderecoDao.getModel());
    }

    private void loadContato() {
        listContato = ContatosDao.lista();
        lstContatos.setModel(ContatosDao.getModel());
        if (listContato.size() > 0) {
            lstContatos.setSelectedIndex(0);
            contato = listContato.get(0);
        }
    }

    private void loadTipoTelefone() {
        tipoTelefoneDao.lista();
        lstTiposEnderecos.setModel(tipoTelefoneDao);
    }

    private void ativaCampos() {
        edtNome.setEnabled(true);
        edtSobrenome.setEnabled(true);
        edtBairro.setEnabled(true);
        edtCEP.setEnabled(true);
        edtCidade.setEnabled(true);
        edtEndereco.setEnabled(true);
        edtEstado.setEnabled(true);
        edtPais.setEnabled(true);
        edtTelefone.setEnabled(true);
        edtTipoEndereco.setEnabled(true);
        edtTipoTelefone.setEnabled(true);
        lstTiposEnderecos.setEnabled(true);
        lstTelefones.setEnabled(true);
        lstTiposTelefones.setEnabled(true);
    }

    private void ativaNomeSobrenome() {
        edtNome.setEnabled(true);
        edtSobrenome.setEnabled(true);
        edtNome.requestFocus();
    }

    private void ativaEndereco() {
        edtBairro.setEnabled(true);
        edtCEP.setEnabled(true);
        edtCidade.setEnabled(true);
        edtEndereco.setEnabled(true);
        edtEstado.setEnabled(true);
        edtPais.setEnabled(true);
        edtTipoEndereco.setEnabled(true);
        ativaOKCancel(Evento.ADDENDERECO, "Adicionar novo endereço!");
    }
    private void desativaEndereco() {
        edtEndereco.setText("");
        edtEndereco.setEnabled(false);
        edtBairro.setText("");
        edtBairro.setEnabled(false);
        edtCEP.setText("");
        edtCEP.setEnabled(false);
        edtCidade.setEnabled(false);
        edtCidade.setText("");        
        edtEstado.setEnabled(false);
        edtEstado.setText("");
        edtPais.setEnabled(false);
        edtPais.setText("");
        edtTipoEndereco.setEnabled(false); 
        edtTipoEndereco.setText("");
        ativaOKCancel(Evento.NULL, "");
    }

    private void ativaTelefone() {
        edtTelefone.setEnabled(true);
        edtTipoTelefone.setEnabled(true);
        lstTelefones.setEnabled(true);
        lstTiposTelefones.setEnabled(true);
    }

    private void desativaCampos() {
        edtNome.setEnabled(false);
        edtSobrenome.setEnabled(false);
        edtBairro.setEnabled(false);
        edtCEP.setEnabled(false);
        edtCidade.setEnabled(false);
        edtEndereco.setEnabled(false);
        edtEstado.setEnabled(false);
        edtPais.setEnabled(false);
        edtTelefone.setEnabled(false);
        edtTipoEndereco.setVisible(false);
        edtTipoTelefone.setVisible(false);
//        lstTipoEnderecos.setEnabled(false);
        lstTelefones.setVisible(false);
//        lstTiposTelefones.setEnabled(false);
    }

    private void desativaNomeSobrenome() {
        edtNome.setEnabled(false);
        edtNome.setText("");
        edtSobrenome.setEnabled(false);
        edtSobrenome.setText("");
    }    

    private void desativaTelefone() {
        edtTelefone.setEnabled(false);
//        edtTipoTelefone.setEnabled(false);
        lstTelefones.setEnabled(false);
    }

    private void limpaTodosCampos() {
        desativaNomeSobrenome();
        edtBairro.setText("");
        edtCEP.setText("");
        edtCidade.setText("");
        edtEndereco.setText("");
        edtEstado.setText("");
        edtPais.setText("");
        edtTelefone.setText("");
        edtTipoEndereco.setText("");
        edtTipoTelefone.setText("");
        lstContatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstTiposEnderecos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        lstTiposTelefones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
    }

    private void insereContato() {
        if (!edtNome.getText().trim().isEmpty() && edtNome.getText().trim().length() > 2 && edtSobrenome.getText().trim().isEmpty() && edtSobrenome.getText().trim().length() > 2) {
            if (ContatoCtrl.insere(edtNome.getText(), edtSobrenome.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Contato salvo com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                loadContato();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar novo contato!", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite o nome e sobrenome do novo contato!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void atualizaContato() {
        if (contato != null && !edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
            contato.setNome(edtNome.getText().trim());
            contato.setSobrenome(edtSobrenome.getText().trim());
            if (ContatosDao.altera(contato)) {
                JOptionPane.showMessageDialog(rootPane, "Contato atualizado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizado contato!", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            desativaNomeSobrenome();
            loadContato();
        }
    }

    private void atualizaContatoGeral() {
        if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
            if (ContatoCtrl.alteraGeral(
                    lstContatos.getSelectedValue(),
                    edtNome.getText(),
                    edtSobrenome.getText())) {
                JOptionPane.showMessageDialog(rootPane, "Contato atualizado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizado contato!", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
            desativaNomeSobrenome();
            loadList2();
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            comando = "";
        }
    }

    private void deletaContato() {
        if (contato != null) {
            if (ContatosDao.deleta(contato.getIdContato())) {
                JOptionPane.showMessageDialog(rootPane, String.format("Contato %s foi apagado com sucesso!", contato.getNome()));
                loadContato();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um contato para apagar!");
        }
    }

    private void insereEndereco() {
        endereco = new Endereco();
        endereco.setEndereco(edtEndereco.getText());
        endereco.setBairro(edtBairro.getText());
        endereco.setCidade(edtCidade.getText());
        endereco.setEstado(edtEstado.getText());
        endereco.setCep(edtCEP.getText());
        endereco.setPais(edtPais.getText());
        endereco.setIdContato(contato.getIdContato());
        endereco.setIdTipoEndereco(tipoEndereco.getIdTipoEndereco());
        if (EnderecoDao.insere(endereco)) {
            JOptionPane.showMessageDialog(rootPane, "Endereço adicionado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao adiciona endereço", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deletaEndereco() {
        boolean retorno;
        retorno = EnderecoDao.deleta(enderecosIndice.get(lstTiposEnderecos.getSelectedIndex()));
        loadContato();
        lblMensagem.setText("");
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);

    }

    private void atualizaEndereco() {
        if (temEndereco) {
            if (!edtEndereco.getText().isEmpty()) {
                Endereco endereco = new Endereco();
                endereco.setIdEndereco(objEndereco.getIdEndereco());
                endereco.setEndereco(edtEndereco.getText());
                endereco.setBairro(edtBairro.getText());
                endereco.setCidade(edtCidade.getText());
                endereco.setEstado(edtEstado.getText());
                endereco.setCep(edtCEP.getText());
                endereco.setPais(edtPais.getText());
                endereco.setIdContato(contatosIndice.get(lstContatos.getSelectedIndex()));
                endereco.setIdTipoEndereco(tiposEnderecosIndice.get(lstTiposEnderecos.getSelectedIndex()));
                EnderecoDao.altera(endereco);
                comando = "";
                btnOK.setEnabled(false);
                btnCancel.setEnabled(false);
                loadContato();
            }
        } else {
            comando = "INSERTADDRESS";
            loadListaTiposEnderecos();
            lblMensagem.setText("Selecione um tipo de endereço.");
        }

    }

    private void insereTipoEndereco() {
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        comando = "";
        edtTipoEndereco.setVisible(false);

        TipoEndereco tipoEndereco = new TipoEndereco();
        tipoEndereco.setTipoEndereco(edtTipoEndereco.getText());
        if (!TipoEnderecoDao.insere(tipoEndereco)) {
            lblMensagem.setText("Tipo de Endereço não cadastrado!");
        }
        loadListaTiposEnderecos();
    }

    private void deletaTipoEndereco() {
        if (lstTiposEnderecos.getSelectedIndex() != -1) {
            if (!EnderecoDao.buscaIDTipoEndereco(tiposEnderecosIndice.get(lstTiposEnderecos.getSelectedIndex()))) {
                TipoEnderecoDao.deleta((tiposEnderecosIndice.get(lstTiposEnderecos.getSelectedIndex())));
            } else {
                lblMensagem.setText("Tipo de Endereço em uso, não pode ser deletado!");
            }
            comando = "";
            indexTiposEnderecos = -1;
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            loadContato();
        }
    }

    private void insereTipoTelefone() {
        TipoTelefone tipoTelefone = new TipoTelefone();
        tipoTelefone.setTipoTelefone(edtTipoTelefone.getText());
        if (!TipoTelefoneDao.insere(tipoTelefone)) {
            lblMensagem.setText("Tipo de Telefone não cadastrado!");
        }
        scrpTiposTelefones.setLocation(300, 510);
        scrpTiposTelefones.setSize(340, 210);
        btnOK.setEnabled(false);
        btnCancel.setEnabled(false);
        comando = "";
        edtTipoTelefone.setEnabled(false);
        loadContato();
    }

    private void deletaTipoTelefone() {
        if (lstTiposTelefones.getSelectedIndex() != -1) {
            if (!TelefoneDao.buscaIDTipoTipo(tiposTelefonesIndice.get(lstTiposTelefones.getSelectedIndex()))) {
                TipoTelefoneDao.deleta((tiposTelefonesIndice.get(lstTiposTelefones.getSelectedIndex())));
            } else {
                lblMensagem.setText("Tipo de Telefone em uso, não pode ser deletado!");
            }
            comando = "";
            indexTiposTelefones = -1;
            btnOK.setEnabled(false);
            btnCancel.setEnabled(false);
            loadContato();
        }
    }

    private void atualizaBotao() {
        if ((lstContatos.getSelectedIndex() == -1
                ? false
                : !lstContatos.getSelectedValue().equals(edtNome.getText() + " " + edtSobrenome.getText()))) {
            if (!edtNome.getText().isEmpty() || !edtSobrenome.getText().isEmpty()) {
                if (comando.equals("")) {
                    ativaOKCancel(Evento.NULL, "Pressione OK para Atualizar");
                }
            }
        } else if (comando.equals("UPDATE")) {
            cancel();
        }

        if (!edtEndereco.getText().equals(objEndereco.getEndereco())
                || !edtBairro.getText().equals(objEndereco.getBairro())
                || !edtCidade.getText().equals(objEndereco.getCidade())
                || !edtEstado.getText().equals(objEndereco.getEstado())
                || !edtPais.getText().equals(objEndereco.getPais())
                || !edtCEP.getText().equals(objEndereco.getCep())) {
            if (!edtEndereco.getText().isEmpty()) {
                if (comando.equals("")) {
                    ativaOKCancel(Evento.UPDATEENDERECO, "Pressione OK para Atualizar");
                }
            }
        } else if (comando.equals("UPDATEADDRESS")) {
            cancel();
        }
    }

    private void listSyncTipoTelefone() {
        if (comando.equals("")) {
            lstTiposTelefones.setSelectedIndex(lstTelefones.getSelectedIndex());
            indexTiposTelefones = lstTiposTelefones.getSelectedIndex();
        }
    }

    private void listSyncTelefone() {
        if (comando.equals("")) {
            lstTelefones.setSelectedIndex(lstTiposTelefones.getSelectedIndex());
            indexTiposTelefones = lstTiposTelefones.getSelectedIndex();
        }
    }

    /**
     * *
     * Criando um efeito de animação para os botões ou texto aumentado sua fonte
     * Botão se o texto for maior que 1 aumenta a fonte para 13 se não para 24
     * JLabel aumenta o texto de 14 para 24.
     *
     * @param obj JLabel ou JButton que deseja que se altere
     * @param isFocus boolean sendo verdadeiro aumenta
     */
    private void isFocus(Object obj, boolean isFocus) {
        if (obj instanceof JLabel) {
            if (isFocus) {
                ((JLabel) obj).setFont(new Font("Arial", 0, 18));
            } else {
                ((JLabel) obj).setFont(new Font("Arial", 0, 14));
            }
        }
        if (obj instanceof JButton) {
            if (isFocus && ((JButton) obj).isEnabled()) {
                if (((JButton) obj).getText().length() > 1) {
                    ((JButton) obj).setFont(new Font("Arial", 0, 13));
                } else {
                    ((JButton) obj).setFont(new Font("Arial", 0, 24));
                }
            } else {
                if (((JButton) obj).getText().length() > 1) {
                    ((JButton) obj).setFont(new Font("Arial", 0, 11));
                } else {
                    ((JButton) obj).setFont(new Font("Arial", 0, 14));
                }
            }
        }
    }

}
